CREATE TABLE discovery.wms_layers (
    id serial,
	csw_url text,
	csw_record_identifier text,
	csw_record_publisher text,
	csw_record_title text,
	csw_record_subjects text,
	csw_record_abstract text,
	csw_record_modified text,
	wms_url text,
	wms_url_domain text,
	wms_layer_for_record_title text,
	wms_layer_for_record_name text,
	wms_access_constraints text,
	only_1_choice bool,
	match_dist text,
	bbox_wgs84 text,
	bbox_projected text,
	wms_get_cap_error bool,
	wms_get_map_error bool,
	made_get_map_req bool,
	image_status text,
	out_image_fname text
);
